### ISSUE TITLE
"Dotmailer connector API endpoint cannot be empty" exception when extension is turned off

### ISSUE THREAD

**Issue by simon-letch** [dotmailer/dotmailer-magento2-extension#495]
Repro steps:
Install Magento 2.2.2
Wait for dotmailer cron jobs to run

Actual result:
Error message in logs - "Dotmailer connector API endpoint cannot be empty"

Expected result:
No error message in logs.

Reported:
https://magento.stackexchange.com/questions/209254/dotmailer-connector-api-endpoint-cannot-be-empty

https://magento.stackexchange.com/questions/209565/magneto-2-2-2-upgrade-failed-due-to-dotmailer-severe-issues-api-endpoint

**Comment by simon-letch** [comment]
@adeelq noticed we're attempting to get the api client without checking if enabled for website first - https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/Model/Newsletter/Subscriber.php#L227

There may be other places. I'll investigate further.

**Comment by kauanguesser** [comment]
It happened to me with a fresh installation of Magento 2.2.2

**Comment by adeelq** [comment]
@kauanguesser Can you please also answer which part of application you got this error?
Cron
Frontend
Admin

**Comment by robbie-thompson** [comment]
@adeelq I can't comment on where others are seeing it, but we're seeing it in var/log/exception.log on our fresh installation.

**Comment by taschert** [comment]
I have the same issue. For me this is the CRON. I get this message every 15 minutes in my execption log.

[2018-01-18 09:15:25] main.CRITICAL: Dotmailer connector API endpoint cannot be empty. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Dotmailer connector API endpoint cannot be empty. at /xxxxxxxxx/vendor/dotmailer/dotmailer-magento2-extension/Model/Apiconnector/Client.php:118)"} []

I also get this message in connector.log :

2018-01-17T01:00:35+00:00 DEBUG (7): getAccountInfo ["GET ACCOUNT INFO for api user :  Authorization has been denied for this request."]

Magento 2.2.2 with the module version 2.3.8

**Comment by worla** [comment]
I am also getting the same error in exception.log after trying to install a new them manually, uploading the files and running `php bin/magento setup:upgrade` .

**Comment by brnuk** [comment]
Same error here - M2.2.2, module 2.3.8

exception.log
main.CRITICAL: Dotmailer connector API endpoint cannot be empty. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Dotmailer connector API endpoint cannot be empty. at /xxxxx/vendor/dotmailer/dotmailer-magento2-extension/Model/Apiconnector/Client.php:118)"}

connector.log 
2018-01-22T14:30:09+00:00 DEBUG (7): getAccountInfo ["GET ACCOUNT INFO for api user :  Authorization has been denied for this request."]

**Comment by SD-dthompson** [comment]
I discovered the same error in my /var/log/exception.log file today. Generally every 15 minutes as for others, though the most recent appears twice practically right on top of itself for some reason: 

[2018-01-22 16:30:10] main.CRITICAL: Dotmailer connector API endpoint cannot be empty. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Dotmailer connector API endpoint cannot be empty. at /home/developer/apps/magento/public/vendor/dotmailer/dotmailer-magento2-extension/Model/Apiconnector/Client.php:118)"} []
[2018-01-22 16:30:11] main.CRITICAL: Dotmailer connector API endpoint cannot be empty. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Dotmailer connector API endpoint cannot be empty. at /home/developer/apps/magento/public/vendor/dotmailer/dotmailer-magento2-extension/Model/Apiconnector/Client.php:118)"} []

/var/log/connector.log seems to match as well 
2018-01-22T16:30:10+00:00 DEBUG (7): getAccountInfo ["GET ACCOUNT INFO for api user :  Authorization has been denied for this request."]
2018-01-22T16:30:11+00:00 DEBUG (7): getAccountInfo ["GET ACCOUNT INFO for api user :  Authorization has been denied for this request."]

it appears to have been happening since the initial installation. Installed from Magento-CE-2.2.2_sample_data-2017-12-11-09-37-31.tar.gz

dotmailer version is 2.3.8 as well.

**Comment by isatbox** [comment]
Hi i have the same error on exception.log
I have upgraded magento 2 from 2.1.7 to 2.1.8 no problem! then 2.1.8 to 2.2.2. It throws some suggestions about dependencies are abandoned sjparkinson/static-review, so i removed it. then run `composer update & php bin/magento setup:upgrade`
then i got this error on installation:
```
Module 'Magento_Integration':
Running schema recurring...Sorry, something went wrong granting permissions. You can find out more in the exceptio
ns log. 
```
Checked the exception log: same error

```
main.CRITICAL: Dotmailer connector API endpoint cannot be empty. {"exception":"[object] (Mag
ento\\Framework\\Exception\\LocalizedException(code: 0): Dotmailer connector API endpoint cannot be empty. at /hom
e/xxxx/xxxx/public_html/vendor/dotmailer/dotmailer-magento2-extension/Model/Apiconnector
/Client.php:118)"} []  
```

can any one help whats going on!

**Comment by adeelq** [comment]
@kauanguesser @robbie-thompson @taschert @worla @isatbox @SD-dthompson @brnuk . We have resolved this and will be releasing soon. 

However in meantime the quickest fix for this is to disable the module in Magento. This is if you are not planning to use this module.

**Comment by cdiacon** [comment]
This been fixed and released now.

**Comment by dylanpedro** [comment]
How do you install the fix on an existing version 2.2.2?

**Comment by cdiacon** [comment]
Hi @dylanpedro 

One of the option will be to get the latest version if you run this on the Magento 2.2.2 version it will run the upgrade to ^2.4 where the issue is fixed : 

```
composer require dotmailer/dotmailer-magento2-extension

```

Let me know if this helps.

**Comment by mikeguy** [comment]
@cdiacon the 'composer require dotmailer/dotmailer-magento2-extension' did not fix my issue.
When I ran magento:setup upgrade I now get:

`Notice: Undefined index: websites in /home/playsports/public_html/magento/vendor/magento/module-config/App/Config/Type/System.php on line 248
`

**Comment by cdiacon** [comment]
@mikeguy 
I mostly sure that is a cache issue, can you clear the cache and generated files before you run this command again?

**Comment by mikeguy** [comment]
@cdiacon 
![image](https://user-images.githubusercontent.com/12158143/36848939-b85b8e94-1d30-11e8-8907-ae777f068333.png)

I tried the following:

```
rm -rf /home/playsports/public_html/magento/var/cache/*
rm -rf /home/playsports/public_html/magento/var/page_cache/*
rm -rf /home/playsports/public_html/magento/var/generation/*
```
then
`magento cache:flush`

and got:
```
 [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "cache" namespace.

Here is the update and exeption logs. I don't know if this dotmailer upgrade to the latest version has fixed the issue since it's still persistant it seems in the log (but that's probably because I can't successfully execture the magento upgrade?) not sure...

The update log I had to trim down, was 50mb, but it was all the same errors.

[exception.log](https://github.com/dotmailer/dotmailer-magento2-extension/files/1771472/exception.log)
[update.log](https://github.com/dotmailer/dotmailer-magento2-extension/files/1771473/update.log)



```

**Comment by cdiacon** [comment]
@mikeguy you are correct that the upgrade is not yet done until you complete the setup:upgrade script then you should not see the "connector API endpoint cannot be empty" message.

assuming you are running the 2.2.2 the generation files moved to this path 

/home/playsports/public_html/magento/generation/*

can you clear generated files also?

**Comment by mikeguy** [comment]
@cdiacon 

So I ran:
```
root@server magento]# rm -rf /home/playsports/public_html/magento/var/cache/*
[root@server magento]# rm -rf /home/playsports/public_html/magento/var/page_cache/*
[root@server magento]# rm -rf /home/playsports/public_html/magento/generation/*
[root@server magento]# rm -rf /home/playsports/public_html/magento/generated/code/*
[root@server magento]# magento setup:upgrade
Notice: Undefined index: websites in /home/playsports/public_html/magento/vendor/magento/module-config/App/Config/Type/System.php on line 248
```

Did I get that right with the /generated/code/*? is that what you meant?

**Comment by cdiacon** [comment]
@mikeguy yes correct,

But I am not sure you need to remove the files manually usually is more related to the upgrade you are trying to do for 2.2.3 and can't see anything related to dotmailer extension.

I am still convinced that this is cache issue try to run this commands and see 
bin/magento cache:clean - is enough no need to use rm -rf

and if you compiled you have to clear this folder 
/generation/code/*

```

**Comment by mikeguy** [comment]
@cdiacon 

```
[root@server magento]# magento cache:clean


  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "cache" namespace.

```

I am not sure why it's not able to run the command 'magento cache:clean'. Is this because I'm stuck in this upgrade cycle that's not complete? 

```
[root@server magento]# composer require magento/product-community-edition 2.2.3 --no-update
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
./composer.json has been updated
[root@server magento]# composer update
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing dotmailer/dotmailer-magento2-extension (2.4.4)
  - Installing dotmailer/dotmailer-magento2-extension (2.4.5)
    Downloading: 100%

Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.
Writing lock file
Generating autoload files

```
I just noticed that dotmailer got upgraded again (from last night) after I ran the composer update.
Anyhow same errors as above, when running upgrade and cache clean...

**Comment by cdiacon** [comment]
@mikeguy 
yes you are right there is no way to complete the command with bin/magento so 
1. should should remove the files from generation/*
2. make sure you have the right permission(I see you are using root user) which may be the problem.

**Comment by mikeguy** [comment]
@cdiacon 

1. cleared:  rm -rf /home/playsports/public_html/magento/generation/*
still no go.
2. OK: I assumed running with root will have all permissions correct, I am aware that it's not the best idea to do so. Can try to get another user setup:

(can you please let me know of a link where I can use as a guide that will ensure I have the right permissions set for this user?) I assume I can do all this via CLI. I also have WHM/Cpanel, not sure if I can create a user in there easier? Anyhow once I have it all setup I can try the upgrade again.

Also another thing I'm thinking is to uninstall this magento install via CLI, but not sure if the commands will work now that i'm stuck here in this state... maybe I can uninstall it using softaculous, but not sure if that will do the right thing and remove everything correctly for when I re-install 2.2.2 again? What do you think?

**Comment by cdiacon** [comment]
@mikeguy sure you can get more information here 
http://devdocs.magento.com/guides/v2.2/config-guide/prod/prod_file-sys-perms.html

**Comment by mikeguy** [comment]
@cdiacon 
after messing around with this for hours, I gave up.
I could not really figure out exactly how to create this file system owner for magento, well I did, but every time I exited out of cli and came back in, it would lose the permissions for that user for some reason.

Anyhow, gave up, installed 2.2.3 directly from softaculous, seems it was available today.

what can I say, every time I ever updated magento2, it's almost like Russian roulette, anyhow thanks for all the help with everything!

**Comment by hamdrew** [comment]
I've looked at the source code for this extension.  The errors you are seeing are definitely coming from the cron jobs.  When determining the API endpoint, the module looks for `connector/api/endpoint` in your **core_config** table.  If not found, it sends a GET request to https://r1-api.dotmailer.com/v2/account-info.  This URL requires authentication, which is not configured if you are not using the module.

You can safely ignore the exceptions in your log.  If you want to squash them, your only option is to disable the module completely (as described above).

I encourage the maintainers to have the cron jobs check if the module is enabled (Configuration -> DotMailer -> API Credentials -> Enabled).  If it is not enabled, the cron jobs should do nothing and return safely.

**Comment by mikeguy** [comment]
@hamdrew 
Thanks for looking at this post.
So I have installed the latest magento 2.2.3 this time, via softaculous, I worked hard at setting the whole store up, added products etc. and this dotmailer was still giving me issues (before I saw this post).

I have tried this time this: 
` magento module:disable Dotdigitalgroup_Email`

Then I ran:
' magento setup:di:compile'

And now I am getting
'Compilation was started.
Interceptors generation... 4/7 [================>-----------]  57% 6 secs 188.0 MiB

  [Exception]
  Warning: array_replace_recursive(): Argument #1 is not an array in /home/playsports/public_html/magento2/vendor/magento/framework/App/DeploymentConfig/Writer.php on line 135


setup:di:compile'

Again I am stuck and my store won't recover, I've must have put more than 8 days of work on this. I feel so defeated, there is no help for this issue now. I'm willing to buy at least two pints for someone who can solve this, please? :-)... desperate here.

**Comment by terrybakshi** [comment]
Same issue on My side too  [2018-03-27 07:45:18] main.CRITICAL: Dotmailer connector API endpoint cannot be empty. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Dotmailer connector API endpoint cannot be empty. at /home/exampledomain/public_html/vendor/dotmailer/dotmailer-magento2-extension/Model/Apiconnector/Client.php:118)"} []

**Comment by hamdrew** [comment]
@mikeguy Apologies for the delayed response. I would be happy to help you! Please contact me off-thread at andrew.hoffmann.wi@gmail.com
